### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by n1ke33** [Snowflake107/discord-tutorial-bot#5]
How do i setup

**Comment by udit2303** [comment]
First of all Install all dependencies by running `npm install` 
Then Enter your token in `index.js` under `client.config` then run `node  index.js`.
**Note:** Chatbot API doesn't work as of now and I'll be making a PR for that

**Comment by n1ke33** [comment]
**i got this error**
node v12.16.1
 

Repl.it: Updating package configuration

--> npm init -y
Wrote to /home/runner/DarkmagentaZigzagDeal/package.json:

{
  "name": "DarkmagentaZigzagDeal",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


--> npm install node-fetch quick.db snowflake-api discord.js hastebin-gen

> better-sqlite3@7.1.1 install /home/runner/DarkmagentaZigzagDeal/node_modules/better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=12.18.3 runtime=node arch=x64 libc= platform=linux)

> better-sqlite3@7.1.1 build-release /home/runner/DarkmagentaZigzagDeal/node_modules/better-sqlite3
> node-gyp rebuild --release

make: Entering directory '/home/runner/DarkmagentaZigzagDeal/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
deps/sqlite3.target.mk:183: recipe for target 'Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o' failed
make: *** [Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o] Error 4
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/runner/DarkmagentaZigzagDeal/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-1019-gcp
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/runner/DarkmagentaZigzagDeal/node_modules/better-sqlite3
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-12-10T10_59_58_901Z-debug.log
npm WARN DarkmagentaZigzagDeal@1.0.0 No description
npm WARN DarkmagentaZigzagDeal@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-12-10T11_00_01_146Z-debug.log
exit status 1


Repl.it: Package operation failed.

**Comment by udit2303** [comment]
repl.it **cannot**  install `better-sqlite3` because it runs out of memory. I would recommend switching to a new host.
On most of the paid hosts, this wouldn't be a problem but if you want a free host, I would recommend something like [BlueFox](https://bluefoxhost.com) which is currently working *fine* for my bot.

**Comment by n1ke33** [comment]
okay thanks do you have a discord that i can contact

**Comment by udit2303** [comment]
The link is the link to their discord

**Comment by n1ke33** [comment]
i mean your discord

**Comment by udit2303** [comment]
> i mean your discord

Here is the invite link to [Snowflake Studio ❄](https://discord.gg/uqB8kxh)

**Comment by n1ke33** [comment]
Hi i tried it but its still not working all i want is a leveling bot
